version: '3.3'

services:
  db1:
    build:
      context: ./sql
    restart: always
    container_name: cooper-lab1
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'coop'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
